---
title: "Dimorphisme sexuel chez les serpents de mer"
author: "Léa Brohez, Amélie Pierson, Théa Rousseau, Pierre Martin"
format:
  pdf:
    documentclass: report
    toc: true
editor: visual
lang: fr
bibliography: references.bib
---

<!--# Un rapport est différent d'un carnet de notes. Il ne s'agit donc pas de faire du copier-coller d'un document vers l'autre. Un rapport de synthèse doit être compréhensible sans devoir lire le carnet de notes. Le rapport de synthèse doit être  rédigé avec un style et une présentation adéquats. -->

## Introduction

<!--% Rédigez l'introduction de ce rapport en 5-6 phrases.-->

La transition évolutive de la vie terrestre vers la vie aquatique a entraîné d'importantes modifications morphologiques et écologiques chez de nombreuses espèces de serpents marins. Ce phénomène est particulièrement marqué chez les serpents hydrophiines élapidés, notamment au sein des aïpysurines des genres *Emydocephalus* et *Aipysurus.*

Pour ces espèces, l'adaptation à la vie marine semble avoir modifié les dynamiques de sélection naturelle et sexuelle, ce qui se traduit par un dimorphisme sexuel.

L'analyse de ces différences morphologiques entre les mâles et les femelles est essentielle pour nous permettre de comprendre les contraintes écologiques et comportementales qui influencent l'évolution des espèces marines. Ainsi, l'étude approfondie de leur morphologie corporelle permettrait de mettre en évidence l'impact des pressions sélectives propres à la vie marine.

## But

<!--% Rédigez le but de ce rapport en 2 phrases.-->

L'objectif de cette analyse est de quantifier et de modéliser le dimorphisme sexuel chez plusieurs espèces de serpents marins des genres *Emydocephalus* et *Aipysurus* à partir de mesures biométriques. Ce travail a pour but de déterminer l'impact précis des mécanismes de sélection sur la morphologie de ces serpents marins.

## Matériel et méthodes

<!--% Cette section doit comprendre deux parties. La première partie doit expliciter les données employées et la seconde traiter des analyses réalisées et des logiciels employés.-->

## Résultats

<!--% Présentez les deux modèles les plus pertinents que vous avez sélectionnés. Structurez la section en deux parties avec deux titres de niveau trois.-->

## Discussion et Conclusion

<!--% En tenant compte du but de votre carnet de notes et de vos résultats, discutez de résultats et proposez des conclusions à votre analyse en 5 à 10 phrases. -->

## Bibliographie
